print ('The basic clean function in this script performs basic cleaning.')
print('It contains some customized trash words.')
basic_clean = function(data){
        data = tolower(data)
        data = gsub('r&b',' ',data)
        data = gsub('r&d',' ',data)
        data = gsub('[^[:alpha:]]',' ',data)
        data = gsub('data analyst','',data)
        data = gsub('data scientist','',data)
        data = gsub('data engineer','',data)
        data = gsub('business analyst','',data)
        data = gsub('analyst|analysts','',data)
        data = gsub('scientist|scientists','',data)
        data = gsub('engineer|engineers','',data)
        data = gsub('religion','',data)
        data = gsub('sex','',data)
        data = gsub('color','',data)
        data = gsub('race','',data)
        data = gsub('employment','',data)
        data = gsub('religion','',data)
        data = gsub('gender','',data)
        data = gsub('equal opportunity','',data)
        data = gsub('national','',data)
        data = gsub('origin',' ',data)
        data = gsub('job description','',data)
        data = gsub('sexual orientation','',data)
        data = gsub('veteran status','',data)
        data = gsub('year|years','',data)
        data = gsub('experience|experiences','',data)
        data = gsub('processes','process',data)
        data = gsub(' r ',' rprogram ',data)
        data.frame(data)       
}

